### PR TITLE
Add equals() and hashCode() improvements.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**

### CODE REVIEW

**Comment by simonpoole** [comment]
The problem with this is https://developer.android.com/reference/java/util/Objects aka available from SDK 19 on, not from 16 which is our current minimum. I just rechecked but as far as I can tell this is not supported in any fashion on earlier SDKs, see also my comment on the other PR.

**Comment by Isira-Seneviratne** [comment]
> The problem with this is https://developer.android.com/reference/java/util/Objects aka available from SDK 19 on, not from 16 which is our current minimum. I just rechecked but as far as I can tell this is not supported in any fashion on earlier SDKs, see also my comment on the other PR.

The Objects methods are desugared for older API levels.

**Comment by simonpoole** [comment]
> The Objects methods are desugared for older API levels, even without library desugaring enabled.

Documentation?

**Comment by Isira-Seneviratne** [comment]
> > The Objects methods are desugared for older API levels, even without library desugaring enabled.
> 
> Documentation?

https://jakewharton.com/static/files/d8_api_desugar_list.txt

Also, I decompiled the app, and the methods were backported, e.g. `Objects.hash()` was rewritten as a call to `Arrays.hashCode()`.

**Comment by simonpoole** [comment]
Can you rebase this on the current master branch and then force push to the PR branch? Thanks.

**Review by simonpoole — CHANGES_REQUESTED** [review]

**Pull request merged**
