### PR TITLE
resurvey drop-down #1101

### PR DESCRIPTION
**Pull request by aarewhyan**
fixed issue #1101 
First started with the use of the spinner class for the drop-down and querying the taginfo class for the values of the selected keys but switched to AutoCompleteTextView and used Preset.getAutocompleteValues() method for querying, which was faster.
Still fixed the Server class to be run Asynchronously for the taginfo class.
Finally added the checkbox to enable, disable resurvey items.
Two questions here:

-  Should I change the keys dropdown to Preset.getObjectKeys and also remove address key?
- Is my implementation of selected field  which required updating the database to version -4 correct?

@simonpoole If you could review this and provide the necessary feedback, while I upload the test file.

### CODE REVIEW

**Comment by aarewhyan** [comment]
checkboxes_50
drop-down_50

**Review by simonpoole — CHANGES_REQUESTED** [review]
The change to Server.java is not necessary and not actually a fix as all methods using openConnection  directly or indirectly are already executed in a separate thread if they are used in a relevant context (aka from the UI). This is preferable as there might be further processing (for example merging downloaded OSM data) that shouldn't be done on the UI thread.

**Comment by aarewhyan** [comment]
I did see the use of separate threads being implemented and thought for the easy fix, I did not take in account for the rest of the processing being done on the same thread.
@simonpoole  What can you say about the rest of the changes and should I change the keys drop-down?

**Comment by simonpoole** [comment]
> What can you say about the rest of the changes and should I change the keys drop-down?

I haven't got around to looking at in detail, will do so later this week.

**Comment by simonpoole** [comment]
Hi, two comments: you should squash the commits that don't add anything additional (aka remove the changes to the server code) with the original commit and then force push. 2nd I think "enabled" or "active" would be a better choice of name for the "selected" field. 

Outside of that, this looks fine.

**Comment by aarewhyan** [comment]
For the selected field I will definitely make the appropriate changes. As for squashing the commits I intended to do that before it is supposed to be merged the thing is, last week I thought of working on this issue #1706 but there seems to be some problem with my gradle build. So all these commits were actually just me trying to see if I had broken the code somewhere. I haven't been able to do any progress. If you don't mind could you point me in the right direction-

This is the error I get on my gradle build- 
image

the stacktrace of this exception is  -
[Exception 1.txt](https://github.com/MarcusWolschon/osmeditor4android/files/11992340/Exception.is.txt)

I also tried running it purely via the gradle wrapper and I got the following exception
 
[Exception 2.txt](https://github.com/MarcusWolschon/osmeditor4android/files/11992342/Exception.2.txt)

If you could point out my mistake I could move onto some other issue and even complete the test file for this patch.

**Comment by simonpoole** [comment]
The 1st problem looks like a gradle version issue, in general I would recommend using the wrapper as a number of the plugins depend strongly on the gradle version.

The 2nd issue is weirder, for debugging I would test if it goes away with maxParallelForks set to one.

**Pull request closed without merging**
