### PR TITLE
update name-suggestion-index data, remove brand:wikidata and brand:wikipedia from nsi tags

### LINKED ISSUE #850: Consider dropping brand:wikidata tags from name-suggestion-index
Wikidata tags are confusing and unverifiable for a typical human, brand:wikidata tags are also fairly useless.

I propose to process name-suggestion-index data and keep only useful tags (all except `brand:wikidata`) to avoid pointless confusing of mappers.

### PR DESCRIPTION
**Pull request by matkoniecz**
This PR is doing two things at once - updates name-suggestion-index (there are any improvements not present in Vespucci, including some fixes of wrong data and while there are some regressions overall it is a string improvement)

It also removes `brand:wikidata` and `brand:wikipedia` tags (I did it using a slightly customized generator of distribution files). In case that this part is unwanted and you prefer to rather close and reject #850 I can make a new pull request that is merely updating nsi.

-------

I compiled Vespucci and verified that name suggestion still works.

-------

fixes #850

almost all of brand:wikidata and brand:wikipedia are
additions with root in name match without verification,
with edits being bot edits or de facto bot edits

it turns them into duplicates of name tag

IMHO there is no good reason to confuse Vespucci mappers with them
during mapping new objects

### CODE REVIEW

**Comment by simonpoole** [comment]
I'm not opposed to this as such. The basic problem is why incorrect brand:* tags are present in the NSI to start with, because obviously this is going to be a big problem with iD, and a one time fix to the version we use doesn't really solve that problem.

**Comment by matkoniecz** [comment]
What is the preferred frequency of PR with nsi updates? On every nsi release (what is quite often)? Every few months?

> The basic problem is why incorrect brand:* tags are present in the NSI

Mistakes (I recently removed links that were describing specific building rather than a bank).

**Comment by simonpoole** [comment]
Can you update this again (for the 13.1 release).

**Comment by matkoniecz** [comment]
Yes, I will do this. I will make PR without `brand:wikidata`, `brand:wikipedia` but I may make rather PR with this tags included.

**Pull request merged**
