### PR TITLE
Intent util

### PR DESCRIPTION
**Pull request by johnjohndoe**
I added the *IntentUtil* class to hide the repetitive creation of Intents and adding extras.

### CODE REVIEW

**Comment by simonpoole** [comment]
Moving the starting of the HelpViewer to a method clearly makes sense, but I would suggest including the startActivity too. From a logic pov though this would belong in the HelpViewer class itself.

Likely a similar argument could be made for the other intents. So instead of creating a largish number of custom named methods that nobody is ever going to remember and are completly detached from the code that actually processes the resultign Intent, what about
HelpViewer.start(..)
Main.start(..)

or similar.

**Comment by johnjohndoe** [comment]
Interesting. I did not think in this direction. I am used to add such a utility class to hide the `Intent` construction including `Bundle` extras. Though, it makes sense to encapsulate stuff within the specific classes. Let me have a look into this and I will send you an update or comment here.

**Comment by simonpoole** [comment]
I don't know if there is an established android pattern for the specific situation, but for example there is such in a similar situation for Fragements where there is a well established pattern ( Fragement.newInstance(...)).

**Comment by johnjohndoe** [comment]
I like to withdraw this pull request in favor of #368.

**Pull request closed without merging**
