### PR TITLE
Use Uri builder to construct search URL.

### PR DESCRIPTION
**Pull request by johnjohndoe**
I extracted this small optimization from pull request #399. So this pull request might be merged first.

### CODE REVIEW

**Comment by johnjohndoe** [comment]
:speak_no_evil: rebased

**Comment by simonpoole** [comment]
Can you rebase this on the current master and I will merge.

**Comment by johnjohndoe** [comment]
Rebased.
As mentioned before: I am totally fine with you rebasing my branch (authorship is not altered).

**Comment by simonpoole** [comment]
@johnjohndoe but rebasing three forks is much faster for you than it is for me ......

**Comment by johnjohndoe** [comment]
No merge?

**Comment by simonpoole** [comment]
Two left thumbs.

**Pull request merged**
