### PR TITLE
Added install links to readme

### PR DESCRIPTION
**Pull request by PeterKW**
>

### CODE REVIEW

**Comment by simonpoole** [comment]
No links to F-Droid please, thanks.

**Comment by PeterKW** [comment]
Okay, not sure how to do that on the GitHub website?

**Comment by simonpoole** [comment]
If you can't do it, I'll squash before merging.

**Comment by simonpoole** [comment]
Replaced by and merged with https://github.com/MarcusWolschon/osmeditor4android/pull/1965

**Pull request closed without merging**
