### PR TITLE
Replace deprecated HttpURLConnection with OkHttpClient.

### PR DESCRIPTION
**Pull request by johnjohndoe**
In this branch I start to introduce [OkHttp](http://square.github.io/okhttp/) as the new HTTP client.

### CODE REVIEW

**Comment by simonpoole** [comment]
Does this work with the OAuth implementation that we use?

**Comment by johnjohndoe** [comment]
I am not justifying adding OkHttp by its "coolness". If OkHttp's feature set as described on the website does not convince you, please watch ["A Few Ok Libraries"](https://www.youtube.com/watch?v=WvyScM_S88c). This convinced me that it does make sense to switch to a modern HTTP client. Please note that further refactoring is needed to benefit from the full power of Okio and OkHttp.

Since I do not want to throw large change sets onto you I limited the refactoring to the search feature. The search does not rely on OAuth as far as I can see. Therefore, I did not look into this until now. Here is a [quick search for "okttp oauth signpost"](http://bfy.tw/3bYS).

**Comment by johnjohndoe** [comment]
@simonpoole @MarcusWolschon Did you have time to make up your mind about this pull request?

**Comment by MarcusWolschon** [comment]
I'm not keen on adding external dependencies but ultimately I leave the
decision to Simon.

**Comment by simonpoole** [comment]
@johnjohndoe Don't panic, I've simply a) not had a look at the code changes b) not looked at the documentation yet. And as a result don't have an opinion yet.

**Comment by johnjohndoe** [comment]
Just for a short notice: I updated the branch to use the latest release of OkHttp 3 and rebased it onto master.

**Comment by friedger** [comment]
HttpUrlConnection is not depreacted AFAIK. (https://developer.android.com/reference/java/net/HttpURLConnection.html). The implementation of HttpURLConnection is using okhttp (https://twitter.com/JakeWharton/status/482563299511250944) since Android 4.4

So, the motivation for this change should be more about moving from UrlConnection to Request/Response API

**Comment by johnjohndoe** [comment]
@friedger Thanks for pointing this out again. I guess the subject of this pull request is kind of "deprecated" ;-/

**Comment by johnjohndoe** [comment]
@simonpoole I rebased the branch again onto master in case you have time to review it.

**Comment by johnjohndoe** [comment]
I updated the commits to use the latest version of [OkHttp](http://square.github.io/okhttp/) (v.3.3.1) and rebased the branch on `master`. Feel free to test it out when you have time.

**Comment by MarcusWolschon** [comment]
Let's merge.
OKHttp hat become the new de-facto standard on Android anyway.

**Comment by johnjohndoe** [comment]
I can review the branch quickly tonight. I will rebase it on top of the latest master then. Stay tuned.

**Comment by johnjohndoe** [comment]
Rebased and force pushed.

**Comment by simonpoole** [comment]
Pro memoria, candidate for Signpost integration https://github.com/pakerfeldt/okhttp-signpost

TODO locate library jars for the various components, otherwise merging this will break the build for everybody not using AndroidStudio.

**Comment by johnjohndoe** [comment]
> ... will break the build for everybody not using AndroidStudio.

Do you mean for people who use another build system then Gradle?
Do you want me to add the OkHttp .jar to the libs folder?

**Comment by simonpoole** [comment]
@johnjohndoe  that was more directed at myself that I nned to include the libraries in the non-gradle build. I have them locally just neet to verify that everything works in both build variants. Which however is likely going to take 2 weeks since I'm on the road for a while.

**Comment by johnjohndoe** [comment]
> ... I have them locally ...

Do you mean as [external projects in the workspace as the support libraries](https://github.com/MarcusWolschon/osmeditor4android/blob/master/project.properties) or as a .jar in the _libs/_ folder?

**Comment by johnjohndoe** [comment]
:+1: Please note that [OkHttp has been updated](https://github.com/square/okhttp/blob/master/CHANGELOG.md) meanwhile.

**Comment by simonpoole** [comment]
@MarcusWolschon 
Testing against 2.2 today unluckily shows that OkHttp relies on java.net.IDN that was added in API 9, so either we need to back the change out, provide a workaround or drop support for 2.2.

**Comment by johnjohndoe** [comment]
Oh! Just to confirm. This means the app will crash whatsoever on devices running Froyo (2.2 – 2.2.3) aka. API level 8?!

**Comment by simonpoole** [comment]
Yes. Naturally right now it has limited impact and likely I'll just make the code build dependent as a short term solution (that naturally makes using okhttp in other places impractical so can only be a quick fix).

**Comment by johnjohndoe** [comment]
Agreed. This should not be the final decision - code becomes a mass. I encourage a discussion about raising the minSdkVersion or against OkHttp (another option might be to discuss the minSdkVersion with the authors).

**Comment by simonpoole** [comment]
The immediate cause (might not be the only one) for the crash is java.net.IDN missing, I suspect that that is really not simple to replace.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/5026bafc45c07e1ba8ff088a4bb8ff55113262a5 migrated everything to OkHttp

**Comment by simonpoole** [comment]
One year later ... it is back to the drawing board, for replacement suggestions https://github.com/MarcusWolschon/osmeditor4android/issues/891

**Pull request merged**
