### PR TITLE
Update project setup

### PR DESCRIPTION
**Pull request by johnjohndoe**
I prepared the following commits to allow to work on the project using Eclipse as well as Android Studio. You can even use Gradle on the command line to build the project - no IDE is needed.

When you decide to fully migrate to Gradle and Android Studio the folder structure must be changed.

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@MarcusWolschon Do you prefer to have pull requests being sent against another branch?

**Comment by simonpoole** [comment]
0.9.6 is the current development branch (and has some larger refactoring
of certain parts of the app, for example to support multi-select),
master is bug fixes only. There are a limited number of things planned
and in work for this release and while the odd new feature and naturally
bug fixes are welcome, adding more stuff that is fundamentally new is
not going to speed things up.

I would (strongly) suggest following the "old" development model till
0.9.6 is out of the door. We can then discuss changing things.

Simon

Am 17.04.2015 um 17:24 schrieb Tobias Preuss:

**Comment by johnjohndoe** [comment]
@simonpoole Please let me know if you want me to prepare another pull request to convert line endings and add the Gradle configuration on the 0.9.6 branch.

**Comment by simonpoole** [comment]
I was intending to cherry pick the commits and merge them with 0.9.6,
just haven't done it yet.

Simon

Am 09.05.2015 um 01:17 schrieb Tobias Preuss:

**Comment by johnjohndoe** [comment]
> When you decide to fully migrate to Gradle and Android Studio the folder structure must be changed.

Did you think about migrating the folder structure? This would allow to use the full feature set of Gradle builds such as flavors, tests right in the project, ...
Please let me know when you decide to do it. I did it many times and can help with it.

**Comment by simonpoole** [comment]
I'm waiting to see what happens with andmore (the eclipse
fork/replacement of the ADT plugin), hopefully that will become clearer
soon.

Simon


Am 03.06.2016 um 18:30 schrieb Tobias Preuss:

**Comment by johnjohndoe** [comment]
Interesting, I have not heard of [andmore](https://projects.eclipse.org/projects/tools.andmore) (since I work with Android Studio).

**Comment by simonpoole** [comment]
While not perfect building with buildship (eclipse gradle integration) seems to work OK. So that everybody has a fighting chance to get used to the idea, I would suggest changing the directory layout after the release of 0.9.8.

Note: that it seems that ACRA actually only supports API 8 and higher meaning we can't support Android 2.1 anymore, but I admit that I've never tested anything below 2.2 in any case.

**Comment by johnjohndoe** [comment]
> ... changing the directory layout ...

That sounds good. I am looking forward to writing a few tests.

> buildship

I just got to know the Eclipse plugin the other day [when I talked to Rene Groeschke](http://www.meetup.com/GDG-Berlin-Android/events/230697455/) from the Gradle team.

**Pull request merged**
