### PR TITLE
Switch from ELI to JOSM Imagery Sources

### PR DESCRIPTION
**Pull request by grischard**
The Editor Layer Index will receive less updates. The JOSM index already has more and more up-to-date layers. Both indexes are under the same CC-BY-SA license, and [Go Map!! has already switched](https://github.com/bryceco/GoMap/pull/295).

### CODE REVIEW

**Comment by simonpoole** [comment]
Small issue, this needs to change the gradle task for updating the imagery too. 

What needs some thinking is pre-filtering more stuff when reading the JSON configuration in to the on device DB. Currently this only drops WMS servers with unsupported projections, WMS endpoints and WMTS servers. But as the JOSM data contains things that are not going to be of any conceivable use for our application, say for example an imagery source that is more than two decades old, filtering more aggressively is nearly a given.

**Comment by grischard** [comment]
Yeah, iD [does that too](https://github.com/openstreetmap/iD/blob/develop/scripts/update_imagery.js), and it makes a lot of sense. There are also tags that Vespucci doesn't use, which could conceivably be dropped.

**Comment by grischard** [comment]
Gradle is failing for something completely unrelated *phew*

**Comment by simonpoole** [comment]
GitHub actions/workflows is notoriously unreliable, there have been days where the build has failed four times in a row because it couldn't retrieve a dependency. And this doesn't actually run any of the integration tests.

**Comment by simonpoole** [comment]
This will be merged once https://github.com/MarcusWolschon/osmeditor4android/pull/1148 is done

**Comment by simonpoole** [comment]
@grischard could you rebase, I'll then merge.

**Comment by grischard** [comment]
Let's try!

**Comment by simonpoole** [comment]
Thanks!

Merged with https://github.com/MarcusWolschon/osmeditor4android/commit/630c38daffdebefb3587d5b3334a7ee4c0ab6100

There were a couple of small issues:

- the rebase was screwed up and was probably a merge which went wrong
- any old eli entries need to be removed when re-creating the on device DB
- not directly related to the PR https://josm.openstreetmap.de/ticket/19011#ticket

**Pull request closed without merging**
