### PR TITLE
Added accepted material for recycling

### PR DESCRIPTION
**Pull request by Mannivu**
I've added the "recycling:drugs" tag for both Recycling Centre and Recycling Container, since is one of the accepted values.

### CODE REVIEW

**Comment by simonpoole** [comment]
Thanks!

**Comment by Mannivu** [comment]
Thank you!

**Comment by simonpoole** [comment]
Upppps the PR is against the wrong repo, the presets are maintained in https://github.com/simonpoole/beautified-JOSM-preset can you recreate the PR their? Thanks.

**Comment by Mannivu** [comment]
Sorry, not so used to github. What should I have to do? Recreate the branch or just edit the files in the https://github.com/simonpoole/beautified-JOSM-preset repo?

**Comment by simonpoole** [comment]
Just edit the files in the other repo, the version here is generated during build and changes would simply be overwritten.

**Comment by Mannivu** [comment]
Ok, I think I've done it.

**Pull request merged**
