### PR TITLE
Resolve lint warnings

### PR DESCRIPTION
**Pull request by johnjohndoe**
I am trying to minimize the number of Lint warnings. Please let me know if you do not agree with certain changes. I am happy to discuss the cases and rewrite the branch.

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@simonpoole I can rebase onto master if you don't mind.

**Comment by simonpoole** [comment]
Doing this against 0.9.7 is the done thing, as we do not want to introduce any new issues  in master at this point in time, and particularly not do a java version change in mid-flight. 

In general it would probably be better if stuff that requires java 7 is separated out in to a separate PR, but that may be too much work at such a late date.

**Comment by johnjohndoe** [comment]
I might set compile options to `1.6` and see which Lint warnings remain. (I will have time to do this after the weekend.)

**Comment by simonpoole** [comment]
Merged all commits that didn't contain 1.7 specific syntax or that hadn't been superseded.

**Comment by johnjohndoe** [comment]
@simonpoole I cannot see how this happened but you mixed up the content of some of the commits when you applied them to `0.9.7`. Please review them in the`0.9.7` branch. For example the `StorageDelegator` changes are present in multiple commits (911cddf7e17c15bbe858a53c426686a8c79c8e24, 077f5e5b08dba228c079b3d0a4ef9359ea50f047, 519cfa6c181045d59ed2c4b56fec366e28475eff).

**Comment by simonpoole** [comment]
IMHO this a result of cherry picking and shoudn't be of concern as long as the net result is correct.

**Comment by simonpoole** [comment]
Hmm I can't quite understand it and take back my earlier comment partially, seems as if there may have a difference in order (even though I just went through the commits and cherry-picked them). Don't think it makes a lot of sense to run after this, whats in master now seems to be net ok.

**Pull request closed without merging**
