### PR TITLE
#1538 Added go to Start/End of Way

### PR DESCRIPTION
**Pull request by aarewhyan**
- Created a Start/End Way menu item, its execution Dailogbox with start and end button and finally added map invalidate and zoomTo functionality.
- Defined necessary literals in the xml files.

### CODE REVIEW

**Review by simonpoole — COMMENTED** [review]
Please never merge a PR branch in to master, always rebase.

**Comment by aarewhyan** [comment]
@simonpoole I had a feeling I wasn't understanding the process when I commented on #1538 issue itself.
Help me out if you can, form what I am understanding I need to create a PR for some different branch (other than master), get it approved then rebase it to the master.

**Comment by simonpoole** [comment]
> @simonpoole I had a feeling I wasn't understanding the process when I commented on #1538 issue itself. Help me out if you can, from what I am understanding I need to create a PR for some different branch (other than master), get it approved then rebase it to the master.

"normal" github workflow is 

- fork target repo on github
- clone to where ever you are working on your changes
- checkout new branch for your changes 
- make commits to that branch
- when the work is at a point were it is reviewable/you want input on it: push it to your forked repo on github (creating the new branch)
- create PR
- iteratively improve the PR by, adding further commits and cleaning up noise by squashing and other changes and force pushing
- rebase on the main development branch (aka where your changes will be merged in to and which you've kept up to date) as necessary, latest immediately before the PR is merged by the maintainer.

Working this way avoids last minute merge conflicts, and if there are conflicts they are handled by the PR author, not by the maintainer, and results in a clean sequential commit history.

**Comment by aarewhyan** [comment]
I did mess up a bit but I have tried to work through the workflow as you have stated and created a new PR.
Maybe now I will adapt better to git.

**Pull request closed without merging**
