### PR TITLE
multithreaded GPX draw

### PR DESCRIPTION
**Pull request by kai-morich**
another improvement for #1418
typical speedup is 1.5x to 3.x

### CODE REVIEW

**Comment by simonpoole** [comment]
Sorry that I haven't got around to reviewing this yet, was busy with the 16.0 Beta.

**Comment by kai-morich** [comment]
So far my change worked with restart, suspend and rotate.

Is `Serializable` really used? To me looks like `transient map` is only initialized here: https://github.com/MarcusWolschon/osmeditor4android/blob/07d84f0b637e9052eddd156d193e975652403760/src/main/java/de/blau/android/layer/gpx/MapOverlay.java#L63

**Comment by simonpoole** [comment]
> 
> 
> So far my change worked with restart, suspend and rotate.
> 
> Is `Serializable` really used? To me looks like `transient map` is only initialized here:
> 
> https://github.com/MarcusWolschon/osmeditor4android/blob/07d84f0b637e9052eddd156d193e975652403760/src/main/java/de/blau/android/layer/gpx/MapOverlay.java#L63

It currently doesn't crash because we instantiate the layer classes normally and just use the deserialized class to set selected specific fields, however there is no guarantee that that will always stay that way and the Serialize contract still needs to be honored. So we don't want to serialize fields that are not serializeable and/or don^t hold any state, they should be transient, and they need to be re-initialized before use. This doesn't necessarily need to be in readObject, matter of fact the way we currently do things it is preferable to not do so.

The GPX layer is currently kind of special (both data and task layer too) in that there can only be one instance of it (and the GPX data is held by the tracker service), there's a plan to refactor the GPX handling to make this slightly more flexible.

**Comment by kai-morich** [comment]
I kept the transient initialization as is, in constructor only. If the Serialize logic is changed, other `MapOverlay` classes also need additional initialization.

**Comment by simonpoole** [comment]
Merged via https://github.com/MarcusWolschon/osmeditor4android/commit/62c406c0a73d25645010246718c69dae6fd5c868

**Pull request closed without merging**
