### PR TITLE
Upload changes dialog cleanup

### PR DESCRIPTION
**Pull request by johnjohndoe**
- Just a few cleanups. No functionality is changed.
- This is the lower part of the branch in #579.

### CODE REVIEW

**Comment by simonpoole** [comment]
Just FYI I'm on vacation till end of next week and just fiddling with "easy" stuff till then.

**Comment by johnjohndoe** [comment]
I rebased this branch on top of master.

**Comment by simonpoole** [comment]
Just to avoid confusion, this is supposed to be applied on top of https://github.com/MarcusWolschon/osmeditor4android/pull/579?

**Comment by johnjohndoe** [comment]
No. Before #579. Please rebase this branch first in case master has grown.

**Comment by simonpoole** [comment]
OK.

**Comment by johnjohndoe** [comment]
Rebased.

**Comment by johnjohndoe** [comment]
I rebased this branch on top of master.

**Pull request closed without merging**
