### PR TITLE
Improve UX of upload changes dialog. Add form field validation.

### PR DESCRIPTION
**Pull request by johnjohndoe**
I refactored the "upload changes" dialog a bit so that the user can scroll the whole content (changes list and form fields). Before it was quite tricky to review the list of changes once the keyboard is open. The screen recording shows the new behavior.

vespucci

### CODE REVIEW

**Comment by simonpoole** [comment]
While this behaviour is in principle better for reviewing the changes, and works as advertised, it forgets why the UI is the way it is (to give a friendly hint that the comment field and best the source field too, needs to be filled out). 

What I think should work reasonably OK, is if the "Upload" button is clicked and the Comment EditText is not visible, to scroll down to the field. focus on it and use a Snackbar to prompt the user to fill it out. Probably there is no harm in doing this even if the EditText is visible, so no need to special case that.

**Comment by johnjohndoe** [comment]
I did not realize that the `Comment` and `Source` form fields are **optional**. Is there any reason why we cannot force the user to fill out them aka. **mandatory** fields? The validation can take place when the `Upload` button is pressed.

**Comment by johnjohndoe** [comment]
I added validation routines (empty not allowed) to both form fields (`Comment`, `Source`). Please have a look at the screen recording to see it in action.

Upload changes, form field validation

**Comment by simonpoole** [comment]
Sorry, haven't got around to looking at the updated PR yet. 

The OSM API doesn't require any specific tags on changesets and the subject has been the subject of a lot of debate over the years and there is a bit of a consensus that at least the comment tag should be present.

IMHO for that reason making it fairly difficult to avoid adding the comment tag is OK.

**Comment by johnjohndoe** [comment]
No worries. I am also a bit more busy within the week.

If I understand you right you would be okay with making the "comment" field a required value. Does the same apply to the "source" field for you?

I am happy to integrate your change requests before merging. Once the branch is fine, feel free to rebase the branch at any time before merging to avoid ugly merge conflicts.

**Comment by simonpoole** [comment]
The basic issue with forcing people to fill things out is that they in the end might simply start adding junk, however there is little we can do wrt that. 

In principle the changes work great, though I would prefer an empty source field just being a warning, However there is a fundamental issue that, once used, both comment and source field are pre-filled from earlier uploads. If you hit upload in such a situation it will do so directly without a chance for you to review the text in the fields (assuming that the number of changes is large enough to hide the EditTexts).

We need to address that somehow.

**Comment by johnjohndoe** [comment]
> ... I would prefer an empty source field just being a warning ...

I will have to investigate for a proper UX pattern for warnings.

> However there is a fundamental issue that, once used, both comment and source field are pre-filled from earlier uploads.

I will try to reproduce that.

> If you hit upload in such a situation it will do so directly ...

But the user still can read and acknowlegde the (prefilled) `Comment` and `Source` values before hitting the `Upload` button?!

**Comment by simonpoole** [comment]
> But the user still can read and acknowlegde the (prefilled) Comment and Source values before hitting the Upload button?!

If they scroll down, yes. IMHO the user should always see those fields (at least once) before upload and it shouldn't be possible to "blindly" upload, don't have a good suggestion just right now.

**Comment by johnjohndoe** [comment]
What do you mean by "blindly"? Can the user confirm the upload from the softkeyboard or is the only way to submit the form pressing the `Upload` button?

**Comment by simonpoole** [comment]
There is an undocumented size limit for the changeset tags that we should check for too given we are touching the code, see https://github.com/MarcusWolschon/osmeditor4android/issues/590

**Comment by johnjohndoe** [comment]
# Design pattern draft
Inspired by the [design guidelines on errors](https://material.io/guidelines/patterns/errors.html#errors-user-input-errors) I could imagine to create a custom `EditText` which shows warnings in addition of errors as shown in the screenshot below.

patterns_errors_userinput12

Please note the screenshot shows the "newer" pattern visualizing the error message below the input form whereas the [screen recording](https://github.com/MarcusWolschon/osmeditor4android/pull/579#issuecomment-312442340) shows the former pattern using the red circle at the end of the input field to indicate an error. If we want to stick to the later - a blue or yellow circle could be used to communicate an information or warning.

**Comment by simonpoole** [comment]
At least testing with an emulator I still have a couple of issues:

- hitting upload with a larger number of changes with empty (so that the comment and source fields are hidden) results in nothing happening - you have to scroll down and see that there are errors to realize what happened
- in the same situation, but after a previous upload, the fields are pre-filled, as a result the changes are uploaded without review of the content of the comment and source field.

IMHO the simplest way to get around this is to scroll to the bottom bring the fields in view if a) there is an issue or if the fields have not been visible yet.

There is a further minor problem in that the error messages seem to get slightly mixed up (arrow pointing up instead of down) if the soft-keyboard is clicked away.

I can provide screen shots if the issues are not clear. Sorry for the nitpicking.

**Comment by simonpoole** [comment]
Maybe we should take a Gordian knot solving approach to this and give up trying to have both the list and the fields on the same page.

So - first review changes .... then hit next and then get the page with Comment and Source field (and potentially any further or user added tags) ... then hit Upload (potentially providing a way to go back to the review page).

Doing it this way would have the further advantage that the dropdowns with previous values wouldn't cause as much conflict with the Soft-Keyboard.

**Comment by simonpoole** [comment]
Merged with https://github.com/MarcusWolschon/osmeditor4android/commit/c676fae6d62a33ac90c06432aba7591ff2ce14f8

**Pull request closed without merging**
