### PR TITLE
create tools option to change locale

### PR DESCRIPTION
**Pull request by zedlabs**
initially I wanted to add this option in the preferences but it required a lot more configuration, so as a test I created it as a menu option in tools 
Also the diff is not showing properly for Main.java, only changes there is the addition of these cases in `onOptionsItemsSelected` -
   ```
     case R.id.menu_tools_locale_cn:
            updateLocale(Locale.CHINA);
            return true;
     case R.id.menu_tools_locale_en:
            updateLocale(Locale.ENGLISH);
            return true;
     case R.id.menu_tools_locale_de:
            updateLocale(Locale.GERMAN);
            return true;
```
related to #915

### CODE REVIEW

**Comment by simonpoole** [comment]
While the selecting needs to be in the preferences in any case, the bigger question is if we want to support anything else than English. Limiting this to "turning off" translations would make things far simpler.

**Comment by simonpoole** [comment]
The consensus seems to be that this should simply be a "Turn translations off" option in the (advanced) preferences, that simply switch to EN.

**Comment by zedlabs** [comment]
sure, I will work on this

**Comment by zedlabs** [comment]
closing, will create a different PR for this

**Pull request closed without merging**
